### ISSUE TITLE
EPIC: Instructor Dashboard (Spreadsheet)

### ISSUE THREAD

**Issue by chundhau** [project-anacapa/anacapa-github-linker#240]
Replicate the Google sheet "Dashboard" available at http://tiny.cc/489teams. This is truly an "instructor" dashboard; only instructors will have access to it. It provides an entry point into both our analytics dashboards and each project's GitHub repo. 

# Frontend, Stories  testable by end user

- [x] There is a team settings page, possibly separate from the existing teams page 
      `/courses/:course_id/teams`.  
      That page builds on top of the existing temporary  `/courses/:course_id/teams` (for debugging).   If it is a separate page, there should be a 
      clear way to navigate to the team settings page. (#245)
- [x] On team setting page, the instructors/admins can enter the url of a project repo. (#245)
- [x] On the instructor dashboard, only teams that have a project assigned should appear, with 
       name of the team, and a link to the project repo.  Teams with no project repo are not listed. (#246)
- [x] On team setting page, add ability to designate the url of a project board (Kanban board)
- [x] Add column to instructor dashboard for quick access to project board (i.e. Kanban board); 
- [x] Add list of team members to instructor dashboard, displaying first name only. 
- [x] Through a mouseover tooltip, the user can see the GitHub ID and full name of each member.
- [ ] Add to the teams setting page, the ability to create "roles" following the UX pattern of "Tags" for issues on GitHub, where each role has a short name, an explanation and a color.  
- [ ] Add to the teams settings page, the ability to assign roles to students.
- [ ] On the instructor dashboard, each team member's icon should show up in the color of the  role they were assigned.  If the student is assigned multiple roles, the color displayed is an arbitrary choice among the roles they have (for now--a "nice to have" feature coming later might be the ability to designate a role.  We'll only build this if it really ends up being needed in practice).
- [ ] On the instructor dashboard, the mouseover should show all team roles assigned to the student.
- [ ] Add the ability to designate, when a student has multiple roles, which of those should be displayed as the student's primary role (the one used for the color) rather than arbitrarily choosing the first role they were assigned.

# Backend, only testable from code, from Postman, or from integration with front end

- [x] Build column in DB to associate each team with a GitHub repo.  #247 
- [x] Add ability to set meeting day and time (in backend) #247 
- [x] Add db column for production (PROD) URL #247 
- [x] Add db column for QA URL #247 
- [x] Add db column for milestone view. #247 
- [x] Add ability to add link to team's chat channel in db and the backend api #247

**Comment by chundhau** [comment]
@ahsun-tariq has created a React prototype that implements this. He demo'd it to me on 5/4/20. He called it the "TeamView Dashboard." He will share URL and codebase for review and discussion.
