### ISSUE TITLE
EPIC: Instructor-Defined Milestone Periods

### ISSUE THREAD

**Issue by chundhau** [project-anacapa/anacapa-github-linker#241]
Instructors need to be able to specify the periods of each milestone or sprint. They do this when they set up Anacapa for a Brownfield project in their course.

- [ ] Ability to add a new milestone period consisting of name, start date and end date
- [ ] Ability to edit a milestone period.
- [ ] Ability to delete a milestone period.
