### ISSUE TITLE
Add "L" fields from Chris' table for issues to the CSV download

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/anacapa-github-linker#283]
In the "publications", under SIGCSE 2021, there is a document tables.docx.

In one of the tables, there are fields for issues marked L.  

We want each of those fields to be available in CSV downloads of issues.

# Acceptance  Criteria

- [ ]  We have in CSV: Created | L | Number of issues created
- [ ]  We have in CSV: Closed | L | Number of issues closed—a coarse-grained measure of task completion
- [ ]  We have in CSV: % with Checklists | L | Percentage of work items decomposed into tasks or acceptance criteria
- [ ]  We have in CSV: % Checklist Items Checked | L | Number of items checked—a fine-grained measure of task completion
- [ ]  We have in CSV: % Assigned to someone | L | Percentage of issues assigned to a team member

# TODOS:

- [ ] Add all of these to the database schema
- [ ]  Add each of these to the graphQL query
- [ ] Add logic to take from GraphQL results and store in database
- [ ] Add fields to CSV download logic

**Comment by pconrad** [comment]
See also issue #284  which relates to commits
