### ISSUE TITLE
CSV Download of Software Development Lifecycle (SDL) events.

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/anacapa-github-linker#287]
In [this document](https://emailwsu.sharepoint.com/:w:/r/teams/eecs.brownfieldproject/Shared%20Documents/Publications/SIGCSE-2021-Brownfield/Tables.docx?d=w9d4dce4b33bb4fb192d1dd8ba9c87eab&csf=1&web=1&e=HyaRRn), there is a table.

This issue focuses on this row (note that the copy/paste below may be out of date, consult live document for updates):

| -- | -- | -- | -- |
|-- | -- | -- | -- |
| GitHub (Events) | Software Development Lifecycle (SDL) Events | L | Total number of GitHub events involving the creation and editing of milestones, issues, pull requests and the project (Kanban) board. |

In this issue, we want to explore which of these events we can get, and ultimately implement a CSV download for "Software Life Cycle Events".

This is an exploratory issue: we'll need to define specifically which events we can get and what fields we want for each event, and add detail to the acceptance criteria as we do.

We can document the GraphQL queries needed in comments on this issue until we are ready to code them.

# TODO 

- [ ] We have GraphQL queries for each SDLC, and a list of the fields we want to store in the database for that event.
- [ ] We have a job to perform the queries and update db
- [ ] We have logic to download the CSV of these queries

**Comment by phtcon** [comment]
A GraphQL Query to get "moved on kanban board" and "created on Kanban board" events:

Note that the details of these moves are only in the API preview, and can't be gotten in the explorer.

```
{
  repository(owner: "ucsb-cs48-s20", name: "project-s0-t1-budget") {
    issues(last: 100) {
      nodes {
        number
        timelineItems(itemTypes: [ADDED_TO_PROJECT_EVENT, MOVED_COLUMNS_IN_PROJECT_EVENT], first: 100) {
          nodes {
            __typename
            ... on AddedToProjectEvent {
              id
              actor {
                login
              }
            }
            ... on MovedColumnsInProjectEvent {
              id
              actor {
                login
              }
              createdAt
            }
          }
        }
      }
    }
  }
}

```
